import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LanguageCode = 'en' | 'hi' | 'mr' | 'gu' | 'ta' | 'te' | 'kn' | 'bn';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
  flag?: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' }
];

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav & General
    portalTitle: 'SocietyOne Portal',
    dashboard: 'Dashboard',
    management: 'Management',
    amenities: 'Amenities',
    residentsAndWings: 'Residents & Wings',
    financeAndAccounting: 'Finance & Accounting',
    amcAndAssets: 'AMC & Assets',
    vendors: 'Vendors',
    tendorManagement: 'Tendor Management',
    userManagement: 'User Management',
    community: 'Community',
    home: 'Home',
    eventsAndNotices: 'Events & Notices',
    events: 'Events',
    fishBowl: 'Fish Bowl',
    services: 'Services',
    facilityBooking: 'Facility Booking',
    helpdesk: 'Helpdesk',
    signOut: 'Sign Out',
    search: 'Search',
    filter: 'Filter',
    all: 'All',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    confirm: 'Confirm',
    close: 'Close',
    back: 'Back',
    status: 'Status',
    pending: 'Pending',
    approved: 'Approved',
    confirmed: 'Confirmed',
    resolved: 'Resolved',
    open: 'Open',
    closed: 'Closed',
    active: 'Active',
    completed: 'Completed',
    language: 'Language',
    selectLanguage: 'Select Language',
    pin: 'PIN',

    // Resident Dashboard
    welcomeBack: 'Welcome back',
    unitNo: 'Unit',
    flat: 'Flat',
    wing: 'Wing',
    resident: 'Resident',
    quickActions: 'Quick Actions',
    payDues: 'Pay Bills',
    bookAmenity: 'Book Facility',
    raiseComplaint: 'Raise Ticket',
    myPasses: 'My Visitors / Passes',
    societyNotices: 'Society Notices',
    emergencyContacts: 'Emergency Contacts',
    recentActivity: 'Recent Activity',
    maintenance: 'Maintenance',
    maintenanceDues: 'Maintenance Dues',
    upcomingEvents: 'Upcoming Events',
    activeBookings: 'Active Bookings',
    noActiveBookings: 'No active bookings yet',
    noUpcomingEvents: 'No upcoming events',
    stayTunedEvents: 'Stay tuned for cultural programs and meetings.',
    notificationsAndNotices: 'Notifications & Notices',
    noNewNotifications: 'No new notifications',
    noticesWillAppear: 'Notices published for your society will appear here.',
    myTickets: 'My Open Tickets',
    myTicketsSub: 'Tickets and repair requests raised by you',
    openTickets: 'Open Tickets',
    openTicketsSub: 'Active tickets raised by other residents in the society',
    noActiveTicketsUser: 'No active tickets created by you',
    everythingSmooth: 'Everything is running smoothly in your unit.',
    needAssistance: 'Need Assistance? Raise a Ticket',
    noOpenTicketsOther: 'No open tickets reported by other residents.',
    update: 'Update',
    gatePass: 'Gate Pass',
    verifiedPass: 'Verified Pass',
    securityGuard: 'Security & Gate',
    helpdeskSupport: 'Helpdesk Support',
    rsvpDetails: 'RSVP / Details',

    // Admin Dashboard
    societyOverview: 'Society Overview',
    totalRevenue: 'Total Revenue',
    pendingApprovals: 'Pending Resident Approvals',
    awaiting: 'Awaiting',
    approveAccessText: 'Approve resident sign-ups below to activate their login access.',
    allUsersAndRequests: 'All Users & Requests',
    whatsHappening: "Here's what's happening in your society today.",
    approve: 'Approve',
    reject: 'Reject',
    approvedSuccess: 'Approved Successfully',

    // Auth & Login / Sign up
    signIn: 'Sign In',
    residentSignUp: 'Resident Sign Up',
    signInToSociety: 'Sign In to Society',
    createResidentAccount: 'Create Resident Account',
    smartPortalSubtitle: 'Smart Housing Society Portal & Resident Management',
    selectSociety: 'Select Society',
    newSocietyQ: 'New Society?',
    chooseSocietyPlaceholder: 'Choose a society...',
    availableSocieties: 'Available Societies',
    searchSocietyPlaceholder: 'Search name, city or pincode...',
    societyPincode: 'Society Pincode',
    availableWings: 'Available Wings',
    residentFullName: 'Resident Full Name',
    mobileNumber: 'Mobile / Phone Number',
    apartmentFlat: 'Apartment / Flat',
    emailUsername: 'Email / Username',
    password: 'Password',
    registrationSubmitted: 'Registration Submitted',
    accessRestricted: 'Access Restricted',
    quickDemoLogins: 'Quick Demo Logins',
    superAdmin: 'Super Admin',
    residentUser: 'Resident User',
    registerNewSociety: 'Register a New Housing Society',
    backToLanding: '← Landing',

    // Landing Page
    landingHeroTitle: 'Smart Housing Society Management Platform',
    landingHeroSubtitle: 'Transform your gated community with seamless facility bookings, automated billing, verified gate passes, and smart resident communication.',
    signInPortal: 'Sign In to Portal',
    registerSocietyBtn: 'Register Society',
    featuresTitle: 'Key Features Built for Modern Societies',
    featuresSubtitle: 'Everything your residential complex needs in one integrated platform.',
    feature1Title: 'Instant Facility Booking',
    feature1Desc: 'Book clubhouses, tennis courts, and swimming pools in real-time.',
    feature2Title: 'Automated Billing & Dues',
    feature2Desc: 'Generate maintenance invoices, pay online, and track expenses effortlessly.',
    feature3Title: 'Digital Helpdesk',
    feature3Desc: 'Raise maintenance tickets, track technician assignments, and resolve issues fast.',
    feature4Title: 'Notices & Community Events',
    feature4Desc: 'Broadcast society circulars, festival schedules, and meeting agendas in seconds.',
    feature5Title: 'Verified Gate Passes',
    feature5Desc: 'Pre-approve guests, delivery personnel, and daily staff with QR gate passes.',
    feature6Title: 'AMC & Asset Tracking',
    feature6Desc: 'Manage equipment warranties, lift maintenance, and vendor contracts seamlessly.',
    getStartedToday: 'Ready to modernize your residential community?',
    joinSocieties: 'Join hundreds of thriving housing societies using SocietyOne today.',

    // Facilities
    availableAmenities: 'Available Amenities',
    bookSlot: 'Book a Slot',
    selectDate: 'Select Date',
    selectTimeSlot: 'Select Time Slot',
    bookingConfirmed: 'Booking Confirmed',
    charges: 'Charges',
    free: 'Free',
    paid: 'Paid',
    perHour: 'per hour',
    timeSlot: 'Time Slot',
    residentName: 'Resident Name',
    amenityName: 'Amenity Name',
    capacity: 'Capacity',
    operatingHours: 'Operating Hours',
    rulesGuidelines: 'Rules & Guidelines',
    myBookings: 'My Bookings',
    cancelBooking: 'Cancel Booking',
    confirmAndBook: 'Confirm & Book',

    // Helpdesk
    raiseNewTicket: 'Raise New Ticket',
    ticketCategory: 'Ticket Category',
    ticketDescription: 'Description',
    ticketUrgency: 'Urgency',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    emergency: 'Emergency',
    inProgress: 'In Progress',

    // Fish Bowl
    communityLounge: 'Community Lounge',
    typeMessage: 'Type your message...',
    sendMessage: 'Send'
  },
  hi: {
    // Nav & General
    portalTitle: 'सोसायटीवन पोर्टल',
    dashboard: 'डैशबोर्ड',
    management: 'प्रबंधन',
    amenities: 'सुविधाएं',
    residentsAndWings: 'निवासी और विंग',
    financeAndAccounting: 'वित्त और लेखा',
    amcAndAssets: 'एएमसी और संपत्ति',
    vendors: 'विक्रेता',
    tendorManagement: 'निविदा प्रबंधन',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    community: 'समुदाय',
    home: 'होम',
    eventsAndNotices: 'कार्यक्रम एवं सूचनाएं',
    events: 'कार्यक्रम',
    fishBowl: 'फिश बाउल चैट',
    services: 'सेवाएं',
    facilityBooking: 'सुविधा बुकिंग',
    helpdesk: 'हेल्पडेस्क',
    signOut: 'लॉग आउट',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    all: 'सभी',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    submit: 'जमा करें',
    confirm: 'पुष्टि करें',
    close: 'बंद करें',
    back: 'वापस',
    status: 'स्थिति',
    pending: 'लंबित',
    approved: 'स्वीकृत',
    confirmed: 'पुष्ट',
    resolved: 'समाधानित',
    open: 'खुला',
    closed: 'बंद',
    active: 'सक्रिय',
    completed: 'पूर्ण',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    pin: 'पिन',

    // Resident Dashboard
    welcomeBack: 'स्वागत है',
    unitNo: 'इकाई',
    flat: 'फ्लैट',
    wing: 'विंग',
    resident: 'निवासी',
    quickActions: 'त्वरित कार्य',
    payDues: 'बिल भुगतान',
    bookAmenity: 'सुविधा बुक करें',
    raiseComplaint: 'टिकट दर्ज करें',
    myPasses: 'मेरे विज़िटर / पास',
    societyNotices: 'सोसायटी सूचनाएं',
    emergencyContacts: 'आपातकालीन संपर्क',
    recentActivity: 'हालिया गतिविधि',
    maintenance: 'रखरखाव',
    maintenanceDues: 'रखरखाव बकाया',
    upcomingEvents: 'आगामी कार्यक्रम',
    activeBookings: 'सक्रिय बुकिंग',
    noActiveBookings: 'कोई सक्रिय बुकिंग नहीं',
    noUpcomingEvents: 'कोई आगामी कार्यक्रम नहीं',
    stayTunedEvents: 'सांस्कृतिक कार्यक्रमों और बैठकों की जानकारी यहाँ मिलेगी।',
    notificationsAndNotices: 'सूचनाएं एवं नोटिस',
    noNewNotifications: 'कोई नई सूचना नहीं',
    noticesWillAppear: 'आपकी सोसायटी के लिए प्रकाशित नोटिस यहाँ दिखाई देंगे।',
    myTickets: 'मेरी खुली शिकायतें',
    myTicketsSub: 'आपके द्वारा दर्ज की गई मरम्मत और सहायता शिकायतें',
    openTickets: 'खुली शिकायतें',
    openTicketsSub: 'सोसायटी के अन्य निवासियों द्वारा दर्ज सक्रिय टिकट',
    noActiveTicketsUser: 'आपके द्वारा कोई सक्रिय टिकट दर्ज नहीं है',
    everythingSmooth: 'आपके फ्लैट में सब कुछ सुचारू रूप से चल रहा है।',
    needAssistance: 'सहायता चाहिए? टिकट दर्ज करें',
    noOpenTicketsOther: 'अन्य निवासियों द्वारा कोई खुली शिकायत नहीं है।',
    update: 'अपडेट',
    gatePass: 'गेट पास',
    verifiedPass: 'सत्यापित पास',
    securityGuard: 'सुरक्षा एवं गेट',
    helpdeskSupport: 'हेल्पडेस्क सहायता',
    rsvpDetails: 'विवरण देखें →',

    // Admin Dashboard
    societyOverview: 'सोसायटी अवलोकन',
    totalRevenue: 'कुल राजस्व',
    pendingApprovals: 'लंबित निवासी अनुमोदन',
    awaiting: 'प्रतीक्षारत',
    approveAccessText: 'लॉगिन अनुमति सक्रिय करने के लिए निवासी पंजीकरण स्वीकृत करें।',
    allUsersAndRequests: 'सभी उपयोगकर्ता और अनुरोध',
    whatsHappening: 'आज आपकी सोसायटी में क्या हो रहा है:',
    approve: 'स्वीकार करें',
    reject: 'अस्वीकार करें',
    approvedSuccess: 'सफलतापूर्वक स्वीकृत',

    // Auth & Login / Sign up
    signIn: 'लॉग इन करें',
    residentSignUp: 'निवासी पंजीकरण',
    signInToSociety: 'सोसायटी में लॉग इन करें',
    createResidentAccount: 'निवासी खाता बनाएं',
    smartPortalSubtitle: 'स्मार्ट हाउसिंग सोसायटी पोर्टल एवं निवासी प्रबंधन',
    selectSociety: 'सोसायटी चुनें',
    newSocietyQ: 'नई सोसायटी?',
    chooseSocietyPlaceholder: 'अपनी सोसायटी चुनें...',
    availableSocieties: 'उपलब्ध सोसायटियां',
    searchSocietyPlaceholder: 'नाम, शहर या पिनकोड खोजें...',
    societyPincode: 'सोसायटी पिनकोड',
    availableWings: 'उपलब्ध विंग',
    residentFullName: 'निवासी का पूरा नाम',
    mobileNumber: 'मोबाइल / फ़ोन नंबर',
    apartmentFlat: 'अपार्टमेंट / फ्लैट नं.',
    emailUsername: 'ईमेल / उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    registrationSubmitted: 'पंजीकरण जमा हो गया',
    accessRestricted: 'पहुंच प्रतिबंधित',
    quickDemoLogins: 'त्वरित डेमो लॉगिन',
    superAdmin: 'सुपर एडमिन',
    residentUser: 'निवासी उपयोगकर्ता',
    registerNewSociety: 'नई हाउसिंग सोसायटी पंजीकृत करें',
    backToLanding: '← मुख्य पृष्ठ',

    // Landing Page
    landingHeroTitle: 'स्मार्ट हाउसिंग सोसायटी प्रबंधन प्लेटफॉर्म',
    landingHeroSubtitle: 'सुविधा बुकिंग, स्वचालित रखरखाव बिलिंग, डिजिटल गेट पास और आसान संवाद के साथ अपनी सोसायटी को स्मार्ट बनाएं।',
    signInPortal: 'पोर्टल में लॉग इन करें',
    registerSocietyBtn: 'सोसायटी रजिस्टर करें',
    featuresTitle: 'आधुनिक सोसायटियों के लिए मुख्य सुविधाएं',
    featuresSubtitle: 'आपकी आवासीय सोसायटी के लिए आवश्यक सभी सुविधाएं एक ही स्थान पर।',
    feature1Title: 'त्वरित सुविधा बुकिंग',
    feature1Desc: 'क्लबहाउस, जिम और स्विमिंग पूल को वास्तविक समय में आसानी से बुक करें।',
    feature2Title: 'स्वचालित बिलिंग और रखरखाव',
    feature2Desc: 'रखरखाव चालान बनाएं, ऑनलाइन भुगतान करें और खर्चों का हिसाब रखें।',
    feature3Title: 'डिजिटल हेल्पडेस्क और शिकायतें',
    feature3Desc: 'मरम्मत टिकट दर्ज करें, तकनीशियन की प्रगति देखें और समस्याओं का शीघ्र समाधान पाएं।',
    feature4Title: 'सोसायटी नोटिस और कार्यक्रम',
    feature4Desc: 'परिपत्र, त्योहार कार्यक्रम और एजीएम बैठकें तुरंत सभी तक पहुंचाएं।',
    feature5Title: 'सत्यापित गेट पास',
    feature5Desc: 'अतिथियों, डिलीवरी कर्मचारियों और घरेलू सहायकों के लिए क्यूआर पास जारी करें।',
    feature6Title: 'एएमसी और संपत्ति प्रबंधन',
    feature6Desc: 'लिफ्ट, जनरेटर, सुरक्षा उपकरण और विक्रेता अनुबंधों का आसान प्रबंधन।',
    getStartedToday: 'क्या आप अपनी सोसायटी को आधुनिक बनाने के लिए तैयार हैं?',
    joinSocieties: 'आज ही SocietyOne से जुड़ें और प्रबंधन को आसान बनाएं।',

    // Facilities
    availableAmenities: 'उपलब्ध सुविधाएं',
    bookSlot: 'स्लॉट बुक करें',
    selectDate: 'तारीख चुनें',
    selectTimeSlot: 'समय स्लॉट चुनें',
    bookingConfirmed: 'बुकिंग पुष्ट हुई',
    charges: 'शुल्क',
    free: 'निःशुल्क',
    paid: 'सशुल्क',
    perHour: 'प्रति घंटा',
    timeSlot: 'समय स्लॉट',
    residentName: 'निवासी का नाम',
    amenityName: 'सुविधा का नाम',
    capacity: 'क्षमता',
    operatingHours: 'कार्य समय',
    rulesGuidelines: 'नियम एवं शर्तें',
    myBookings: 'मेरी बुकिंग',
    cancelBooking: 'बुकिंग रद्द करें',
    confirmAndBook: 'पुष्टि करें और बुक करें',

    // Helpdesk
    raiseNewTicket: 'नयी शिकायत दर्ज करें',
    ticketCategory: 'श्रेणी',
    ticketDescription: 'विवरण',
    ticketUrgency: 'प्राथमिकता',
    low: 'निम्न',
    medium: 'मध्यम',
    high: 'उच्च',
    emergency: 'आपातकालीन',
    inProgress: 'प्रगति पर',

    // Fish Bowl
    communityLounge: 'सामुदायिक लाउंज',
    typeMessage: 'संदेश टाइप करें...',
    sendMessage: 'भेजें'
  },
  mr: {
    portalTitle: 'सोसायटीवन पोर्टल',
    dashboard: 'डॅशबोर्ड',
    management: 'व्यवस्थापन',
    amenities: 'सुविधा',
    residentsAndWings: 'रहिवासी आणि विंग',
    financeAndAccounting: 'वित्त आणि लेखा',
    amcAndAssets: 'एएमसी आणि मालमत्ता',
    vendors: 'विक्रेते',
    tendorManagement: 'निविदा व्यवस्थापन',
    userManagement: 'वापरकर्ता व्यवस्थापन',
    community: 'समुदाय',
    home: 'मुख्यपृष्ठ',
    eventsAndNotices: 'कार्यक्रम आणि सूचना',
    events: 'कार्यक्रम',
    fishBowl: 'फिश बाऊल गप्पा',
    services: 'सेवा',
    facilityBooking: 'सुविधा बुकिंग',
    helpdesk: 'हेल्पडेस्क',
    signOut: 'बाहेर पडा',
    search: 'शोधा',
    filter: 'फिल्टर',
    all: 'सर्व',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    submit: 'सादर करा',
    confirm: 'निश्चित करा',
    close: 'बंद करा',
    back: 'मागे',
    status: 'स्थिती',
    pending: 'प्रलंबित',
    approved: 'मंजूर',
    confirmed: 'निश्चित',
    resolved: 'निवारण झाले',
    open: 'उघडे',
    closed: 'बंद',
    active: 'सक्रिय',
    completed: 'पूर्ण',
    language: 'भाषा',
    selectLanguage: 'भाषा निवडा',
    pin: 'पिन',

    welcomeBack: 'स्वागत आहे',
    unitNo: 'फ्लॅट क्र.',
    flat: 'फ्लॅट',
    wing: 'विंग',
    resident: 'रहिवासी',
    quickActions: 'जलद कृती',
    payDues: 'बिल भरा',
    bookAmenity: 'सुविधा बुक करा',
    raiseComplaint: 'तक्रार नोंदवा',
    myPasses: 'माझे पासेस',
    societyNotices: 'सोसायटी सूचना',
    emergencyContacts: 'तातडीचे संपर्क',
    recentActivity: 'अलीकडील घडामोडी',
    maintenance: 'देखभाल',
    maintenanceDues: 'देखभाल बाकी',
    upcomingEvents: 'आगामी कार्यक्रम',
    activeBookings: 'सक्रिय बुकिंग',
    noActiveBookings: 'सध्या कोणतीही सक्रिय बुकिंग नाही',
    noUpcomingEvents: 'कोणतेही आगामी कार्यक्रम नाहीत',
    stayTunedEvents: 'सांस्कृतिक कार्यक्रम आणि बैठकींची माहिती येथे मिळेल.',
    notificationsAndNotices: 'सूचना आणि परिपत्रके',
    noNewNotifications: 'नवीन सूचना नाहीत',
    noticesWillAppear: 'सोसायटीच्या सूचना येथे दिसतील.',
    myTickets: 'माझ्या तक्रारी',
    myTicketsSub: 'तुम्ही दाखल केलेल्या दुरुस्ती आणि तक्रारी',
    openTickets: 'इतर तक्रारी',
    openTicketsSub: 'सोसायटीच्या इतर सदस्यांनी दाखल केलेल्या तक्रारी',
    noActiveTicketsUser: 'तुमची कोणतीही प्रलंबित तक्रार नाही',
    everythingSmooth: 'तुमच्या फ्लॅटमध्ये सर्व काही सुरळीत सुरू आहे.',
    needAssistance: 'मदत हवी आहे? तक्रार नोंदवा',
    noOpenTicketsOther: 'इतर सदस्यांची कोणतीही तक्रार नाही.',
    update: 'अपडेट',
    gatePass: 'गेट पास',
    verifiedPass: 'सत्यापित पास',
    securityGuard: 'सुरक्षा आणि गेट',
    helpdeskSupport: 'हेल्पडेस्क मदत',
    rsvpDetails: 'तपशील पहा →',

    societyOverview: 'सोसायटी विहंगावलोकन',
    totalRevenue: 'एकूण उत्पन्न',
    pendingApprovals: 'प्रलंबित रहिवासी मान्यता',
    awaiting: 'प्रतीक्षेत',
    approveAccessText: 'रहिवाशांना प्रवेश देण्यासाठी मान्यता द्या.',
    allUsersAndRequests: 'सर्व वापरकर्ते आणि विनंत्या',
    whatsHappening: 'आज सोसायटीतील ठळक घडामोडी:',
    approve: 'मंजूर करा',
    reject: 'नाकारा',
    approvedSuccess: 'यशस्वीरीत्या मंजूर',

    signIn: 'लॉग इन करा',
    residentSignUp: 'रहिवासी नोंदणी',
    signInToSociety: 'सोसायटीमध्ये लॉग इन करा',
    createResidentAccount: 'रहिवासी खाते तयार करा',
    smartPortalSubtitle: 'स्मार्ट हाउसिंग सोसायटी पोर्टल आणि रहिवासी व्यवस्थापन',
    selectSociety: 'सोसायटी निवडा',
    newSocietyQ: 'नवीन सोसायटी?',
    chooseSocietyPlaceholder: 'सोसायटी निवडा...',
    availableSocieties: 'उपलब्ध सोसायट्या',
    searchSocietyPlaceholder: 'नाव, शहर किंवा पिनकोड शोधा...',
    societyPincode: 'सोसायटी पिनकोड',
    availableWings: 'उपलब्ध विंग',
    residentFullName: 'रहिवाशाचे पूर्ण नाव',
    mobileNumber: 'मोबाईल / फोन नंबर',
    apartmentFlat: 'फ्लॅट नंबर',
    emailUsername: 'ईमेल / वापरकर्ता नाव',
    password: 'पासवर्ड',
    registrationSubmitted: 'नोंदणी सादर झाली',
    accessRestricted: 'प्रवेश मर्यादित',
    quickDemoLogins: 'डेमो लॉगिन',
    superAdmin: 'सुपर ॲडमिन',
    residentUser: 'रहिवासी वापरकर्ता',
    registerNewSociety: 'नवीन सोसायटी नोंदवा',
    backToLanding: '← मुख्य पृष्ठ',

    landingHeroTitle: 'स्मार्ट हाउसिंग सोसायटी व्यवस्थापन प्रणाली',
    landingHeroSubtitle: 'सुविधा बुकिंग, देखभाल बिलिंग, डिजिटल गेट पास आणि सुलभ संवादाने सोसायटी व्यवस्थापन करा अधिक सोपे.',
    signInPortal: 'पोर्टलमध्ये प्रवेश करा',
    registerSocietyBtn: 'सोसायटी नोंदवा',
    featuresTitle: 'आधुनिक सोसायट्यांसाठी वैशिष्ट्ये',
    featuresSubtitle: 'आपल्या सोसायटीच्या सर्व गरजा एकाच ठिकाणी.',
    feature1Title: 'त्वरित सुविधा बुकिंग',
    feature1Desc: 'क्लबहाऊस, हॉल आणि क्रीडांगण ऑनलाइन बुक करा.',
    feature2Title: 'देखभाल बिलिंग',
    feature2Desc: 'पावती मिळवा आणि ऑनलाइन देखभाल शुल्क भरा.',
    feature3Title: 'डिजिटल तक्रार निवारण',
    feature3Desc: 'तक्रार दाखल करा आणि तत्पर दुरुस्ती मिळवा.',
    feature4Title: 'सोसायटी सूचना व कार्यक्रम',
    feature4Desc: 'सोसायटीचे सर्व निर्णय आणि कार्यक्रम सर्वांपर्यंत पोहोचवा.',
    feature5Title: 'गेट पास',
    feature5Desc: 'पाहुणे आणि कर्मचाऱ्यांसाठी डिजिटल सुरक्षित पास.',
    feature6Title: 'एएमसी आणि मालमत्ता',
    feature6Desc: 'सोसायटीच्या उपकरणांची सुरक्षित देखभाल.',
    getStartedToday: 'सोसायटीचे व्यवस्थापन स्मार्ट करण्यास तयार आहात?',
    joinSocieties: 'आजच SocietyOne शी जोडा.',

    availableAmenities: 'उपलब्ध सुविधा',
    bookSlot: 'स्लॉट बुक करा',
    selectDate: 'तारीख निवडा',
    selectTimeSlot: 'वेळ निवडा',
    bookingConfirmed: 'बुकिंग निश्चित झाली',
    charges: 'दर',
    free: 'मोफत',
    paid: 'सशुल्क',
    perHour: 'प्रति तास',
    timeSlot: 'वेळ स्लॉट',
    residentName: 'रहिवाशाचे नाव',
    amenityName: 'सुविधेचे नाव',
    capacity: 'क्षमता',
    operatingHours: 'वेळापत्रक',
    rulesGuidelines: 'नियम आणि अटी',
    myBookings: 'माझी बुकिंग',
    cancelBooking: 'बुकिंग रद्द करा',
    confirmAndBook: 'पुष्टी करा आणि बुक करा',

    raiseNewTicket: 'नवीन तक्रार दाखल करा',
    ticketCategory: 'प्रवर्ग',
    ticketDescription: 'तपशील',
    ticketUrgency: 'तातडी',
    low: 'कमी',
    medium: 'मध्यम',
    high: 'जास्त',
    emergency: 'अति तातडीची',
    inProgress: 'प्रगतीत आहे',

    communityLounge: 'समुदाय संवाद',
    typeMessage: 'संदेश लिहा...',
    sendMessage: 'पाठवा'
  },
  gu: {
    portalTitle: 'સોસાયટીવન પોર્ટલ',
    dashboard: 'ડેશબોર્ડ',
    management: 'સંચાલન',
    amenities: 'સુવિધાઓ',
    residentsAndWings: 'રહેવાસીઓ અને વિંગ',
    financeAndAccounting: 'નાણાં અને એકાઉન્ટિંગ',
    amcAndAssets: 'એએમસી અને સંપત્તિ',
    vendors: 'વિક્રેતાઓ',
    tendorManagement: 'ટેન્ડર સંચાલન',
    userManagement: 'યુઝર મેનેજમેન્ટ',
    community: 'સમુદાય',
    home: 'મુખ્ય પૃષ્ઠ',
    eventsAndNotices: 'ઇવેન્ટ્સ અને સૂચનાઓ',
    events: 'ઇવેન્ટ્સ',
    fishBowl: 'ફિશ બાઉલ ચેટ',
    services: 'સેવાઓ',
    facilityBooking: 'સુવિધા બુકિંગ',
    helpdesk: 'હેલ્પડેસ્ક',
    signOut: 'સાઇન આઉટ',
    search: 'શોધો',
    filter: 'ફિલ્ટર',
    all: 'બધા',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    submit: 'સબમિટ કરો',
    confirm: 'પુષ્ટિ કરો',
    close: 'બંધ કરો',
    back: 'પાછા',
    status: 'સ્થિતિ',
    pending: 'બાકી',
    approved: 'મંજૂર',
    confirmed: 'પુષ્ટ',
    resolved: 'ઉકેલાયેલ',
    open: 'ખુલ્લું',
    closed: 'બંધ',
    active: 'સક્રિય',
    completed: 'પૂર્ણ',
    language: 'ભાષા',
    selectLanguage: 'ભાષા પસંદ કરો',
    pin: 'પીન',

    welcomeBack: 'સ્વાગત છે',
    unitNo: 'એકમ',
    flat: 'ફ્લેટ',
    wing: 'વિંગ',
    resident: 'રહેવાસી',
    quickActions: 'ઝડપી ક્રિયાઓ',
    payDues: 'બિલ ચૂકવો',
    bookAmenity: 'સુવિધા બુક કરો',
    raiseComplaint: 'ફરિયાદ નોંધાવો',
    myPasses: 'મારા પાસ',
    societyNotices: 'સોસાયટી સૂચનાઓ',
    emergencyContacts: 'કટોકટી સંપર્કો',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    maintenance: 'મેન્ટેનન્સ',
    maintenanceDues: 'મેન્ટેનન્સ બાકી',
    upcomingEvents: 'આગામી ઇવેન્ટ્સ',
    activeBookings: 'સક્રિય બુકિંગ',
    noActiveBookings: 'હજી સુધી કોઈ સક્રિય બુકિંગ નથી',
    noUpcomingEvents: 'કોઈ આગામી ઇવેન્ટ નથી',
    stayTunedEvents: 'કાર્યક્રમો અને મીટિંગ્સની માહિતી અહીં ઉપલબ્ધ થશે.',
    notificationsAndNotices: 'સૂચનાઓ અને નોટિસ',
    noNewNotifications: 'કોઈ નવી સૂચના નથી',
    noticesWillAppear: 'સોસાયટીની નોટિસ અહીં દેખાશે.',
    myTickets: 'મારી ફરિયાદો',
    myTicketsSub: 'તમારા દ્વારા નોંધાયેલી ફરિયાદો',
    openTickets: 'ખુલ્લી ફરિયાદો',
    openTicketsSub: 'અન્ય રહેવાસીઓ દ્વારા નોંધાયેલી ફરિયાદો',
    noActiveTicketsUser: 'તમારી કોઈ સક્રિય ફરિયાદ નથી',
    everythingSmooth: 'તમારા ફ્લેટમાં બધું બરાબર ચાલી રહ્યું છે.',
    needAssistance: 'મદદ જોઈએ છે? ફરિયાદ નોંધાવો',
    noOpenTicketsOther: 'અન્ય રહેવાસીઓની કોઈ ફરિયાદ નથી.',
    update: 'અપડેટ',
    gatePass: 'ગેટ પાસ',
    verifiedPass: 'ચકાસાયેલ પાસ',
    securityGuard: 'સિક્યોરિટી અને ગેટ',
    helpdeskSupport: 'હેલ્પડેસ્ક સપોર્ટ',
    rsvpDetails: 'વિગતો જુઓ →',

    societyOverview: 'સોસાયટી ઝાંખી',
    totalRevenue: 'કુલ આવક',
    pendingApprovals: 'બાકી રહેવાસી મંજૂરીઓ',
    awaiting: 'રાહ જોઈ રહ્યા છે',
    approveAccessText: 'લૉગિન ઍક્સેસ સક્રિય કરવા માટે મંજૂરી આપો.',
    allUsersAndRequests: 'બધા વપરાશકર્તાઓ',
    whatsHappening: 'આજે તમારી સોસાયટીમાં શું ચાલી રહ્યું છે:',
    approve: 'મંજૂર કરો',
    reject: 'નકારો',
    approvedSuccess: 'સફળતાપૂર્વક મંજૂર',

    signIn: 'સાઇન ઇન',
    residentSignUp: 'રહેવાસી સાઇન અપ',
    signInToSociety: 'સોસાયટીમાં લૉગ ઇન કરો',
    createResidentAccount: 'ખાતું બનાવો',
    smartPortalSubtitle: 'સ્માર્ટ હાઉસિંગ સોસાયટી પોર્ટલ',
    selectSociety: 'સોસાયટી પસંદ કરો',
    newSocietyQ: 'નવી સોસાયટી?',
    chooseSocietyPlaceholder: 'સોસાયટી પસંદ કરો...',
    availableSocieties: 'ઉપલબ્ધ સોસાયટીઓ',
    searchSocietyPlaceholder: 'નામ, શહેર કે પીનકોડ શોધો...',
    societyPincode: 'સોસાયટી પીનકોડ',
    availableWings: 'ઉપલબ્ધ વિંગ',
    residentFullName: 'રહેવાસીનું પૂરું નામ',
    mobileNumber: 'મોબાઇલ નંબર',
    apartmentFlat: 'ફ્લેટ નંબર',
    emailUsername: 'ઇમેઇલ / વપરાશકર્તા નામ',
    password: 'પાસવર્ડ',
    registrationSubmitted: 'નોંધણી સબમિટ થઈ',
    accessRestricted: 'ઍક્સેસ પ્રતિબંધિત',
    quickDemoLogins: 'ડેમો લૉગિન',
    superAdmin: 'સુપર એડમિન',
    residentUser: 'રહેવાસી વપરાશકર્તા',
    registerNewSociety: 'નવી સોસાયટી નોંધાવો',
    backToLanding: '← મુખ્ય પૃષ્ઠ',

    landingHeroTitle: 'સ્માર્ટ હાઉસિંગ સોસાયટી મેનેજમેન્ટ પ્લેટફોર્મ',
    landingHeroSubtitle: 'સુવિધા બુકિંગ, મેન્ટેનન્સ બિલિંગ અને ડિજિટલ ગેટ પાસ વડે તમારી સોસાયટીને સ્માર્ટ બનાવો.',
    signInPortal: 'પોર્ટલમાં લૉગ ઇન કરો',
    registerSocietyBtn: 'સોસાયટી રજીસ્ટર કરો',
    featuresTitle: 'આધુનિક સોસાયટીઓ માટે મુખ્ય સુવિધાઓ',
    featuresSubtitle: 'તમારી સોસાયટી માટે જરૂરી બધું એક જ જગ્યાએ.',
    feature1Title: 'ઇન્સ્ટન્ટ સુવિધા બુકિંગ',
    feature1Desc: 'ક્લબહાઉસ, જિમ અને પાર્ટી પ્લોટ સરળતાથી બુક કરો.',
    feature2Title: 'મેન્ટેનન્સ બિલિંગ',
    feature2Desc: 'ઓનલાઇન બિલ ચૂકવો અને હિસાબ રાખો.',
    feature3Title: 'ડિજિટલ હેલ્પડેસ્ક',
    feature3Desc: 'સમસ્યાઓ માટે ફરિયાદ નોંધાવો અને ઉકેલ મેળવો.',
    feature4Title: 'સોસાયટી સૂચનાઓ',
    feature4Desc: 'પરિપત્રો અને મીટિંગ્સની માહિતી તરત મેળવો.',
    feature5Title: 'ડિજિટલ ગેટ પાસ',
    feature5Desc: 'મહેમાનો અને સ્ટાફ માટે સલામત QR પાસ.',
    feature6Title: 'એએમસી અને સંપત્તિ',
    feature6Desc: 'લિફ્ટ અને સાધનોનું સમયસર મેન્ટેનન્સ.',
    getStartedToday: 'તમારી સોસાયટીને સ્માર્ટ બનાવવા તૈયાર છો?',
    joinSocieties: 'આજે જ SocietyOne સાથે જોડાઓ.',

    availableAmenities: 'ઉપલબ્ધ સુવિધાઓ',
    bookSlot: 'સ્લોટ બુક કરો',
    selectDate: 'તારીખ પસંદ કરો',
    selectTimeSlot: 'સમય પસંદ કરો',
    bookingConfirmed: 'બુકિંગ કન્ફર્મ થયું',
    charges: 'શુલ્ક',
    free: 'મફત',
    paid: 'ચૂકવણીપાત્ર',
    perHour: 'પ્રતિ કલાક',
    timeSlot: 'સમય સ્લોટ',
    residentName: 'રહેવાસીનું નામ',
    amenityName: 'સુવિધાનું નામ',
    capacity: 'ક્ષમતા',
    operatingHours: 'સમય',
    rulesGuidelines: 'નિયમો',
    myBookings: 'મારી બુકિંગ',
    cancelBooking: 'બુકિંગ રદ કરો',
    confirmAndBook: 'પુષ્ટિ કરો અને બુક કરો',

    raiseNewTicket: 'નવી ફરિયાદ નોંધાવો',
    ticketCategory: 'શ્રેણી',
    ticketDescription: 'વર્ણન',
    ticketUrgency: 'પ્રાથમિકતા',
    low: 'ઓછી',
    medium: 'મધ્યમ',
    high: 'ઉચ્ચ',
    emergency: 'કટોકટી',
    inProgress: 'પ્રગતિમાં',

    communityLounge: 'સમુદાય લાઉન્જ',
    typeMessage: 'સંદેશ લખો...',
    sendMessage: 'મોકલો'
  },
  ta: {
    portalTitle: 'சொசைட்டிஒன் போர்டல்',
    dashboard: 'டாஷ்போர்டு',
    management: 'மேலாண்மை',
    amenities: 'வசதிகள்',
    residentsAndWings: 'குடியிருப்பாளர்கள் & பிரிவுகள்',
    financeAndAccounting: 'நிதி & கணக்குகள்',
    amcAndAssets: 'ஏஎம்சி & சொத்துக்கள்',
    vendors: 'விற்பனையாளர்கள்',
    tendorManagement: 'டெண்டர் மேலாண்மை',
    userManagement: 'பயனர் மேலாண்மை',
    community: 'சமூகம்',
    home: 'முகப்பு',
    eventsAndNotices: 'நிகழ்வுகள் & அறிவிப்புகள்',
    events: 'நிகழ்வுகள்',
    fishBowl: 'ஃபிஷ் பவுல் அரட்டை',
    services: 'சேவைகள்',
    facilityBooking: 'வசதி முன்பதிவு',
    helpdesk: 'உதவி மையம்',
    signOut: 'வெளியேறு',
    search: 'தேடு',
    filter: 'வடிகட்டு',
    all: 'அனைத்தும்',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    submit: 'சமர்ப்பி',
    confirm: 'உறுதி செய்',
    close: 'மூடு',
    back: 'பின்செல்',
    status: 'நிலை',
    pending: 'நிலுவையில்',
    approved: 'அங்கீகரிக்கப்பட்டது',
    confirmed: 'உறுதியானது',
    resolved: 'தீர்க்கப்பட்டது',
    open: 'திறந்த',
    closed: 'மூடப்பட்டது',
    active: 'செயலில்',
    completed: 'முடிந்தது',
    language: 'மொழி',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    pin: 'பின்',

    welcomeBack: 'மீண்டும் வருக',
    unitNo: 'அலகு',
    flat: 'பிளாட்',
    wing: 'பிரிவு',
    resident: 'குடியிருப்பாளர்',
    quickActions: 'விரைவு செயல்கள்',
    payDues: 'கட்டணம் செலுத்து',
    bookAmenity: 'வசதி முன்பதிவு செய்',
    raiseComplaint: 'புகார் அளிக்கவும்',
    myPasses: 'என் பாஸ்கள்',
    societyNotices: 'சங்க அறிவிப்புகள்',
    emergencyContacts: 'அவசர தொடர்புகள்',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    maintenance: 'பராமரிப்பு',
    maintenanceDues: 'பராமரிப்பு நிலுவை',
    upcomingEvents: 'வரவிருக்கும் நிகழ்வுகள்',
    activeBookings: 'செயலில் உள்ள முன்பதிவுகள்',
    noActiveBookings: 'இன்னும் முன்பதிவு இல்லை',
    noUpcomingEvents: 'வரவிருக்கும் நிகழ்வுகள் இல்லை',
    stayTunedEvents: 'நிகழ்வுகள் பற்றிய தகவல்கள் இங்கே தோன்றும்.',
    notificationsAndNotices: 'அறிவிப்புகள் & தகவல்கள்',
    noNewNotifications: 'புதிய அறிவிப்புகள் இல்லை',
    noticesWillAppear: 'சங்கத்தின் அறிவிப்புகள் இங்கே வெளியிடப்படும்.',
    myTickets: 'என் புகார்கள்',
    myTicketsSub: 'நீங்கள் பதிவு செய்த புகார்கள்',
    openTickets: 'திறந்த புகார்கள்',
    openTicketsSub: 'பிற குடியிருப்பாளர்களின் புகார்கள்',
    noActiveTicketsUser: 'உங்களுக்கு செயலில் உள்ள புகார்கள் இல்லை',
    everythingSmooth: 'உங்கள் இல்லத்தில் அனைத்தும் நலமாக உள்ளது.',
    needAssistance: 'உதவி தேவையா? புகார் அளிக்கவும்',
    noOpenTicketsOther: 'பிற குடியிருப்பாளர்களின் புகார்கள் இல்லை.',
    update: 'புதுப்பிப்பு',
    gatePass: 'கேட் பாஸ்',
    verifiedPass: 'சரிபார்க்கப்பட்ட பாஸ்',
    securityGuard: 'பாதுகாப்பு & கேட்',
    helpdeskSupport: 'உதவி மையம் ஆதரவு',
    rsvpDetails: 'விவரங்கள் →',

    societyOverview: 'சங்க கண்ணோட்டம்',
    totalRevenue: 'மொத்த வருவாய்',
    pendingApprovals: 'நிலுவையில் உள்ள ஒப்புதல்கள்',
    awaiting: 'காத்திருக்கிறது',
    approveAccessText: 'பயனரை அங்கீகரிக்கவும்.',
    allUsersAndRequests: 'அனைத்து பயனர்கள்',
    whatsHappening: 'இன்றைய முக்கிய நிகழ்வுகள்:',
    approve: 'அங்கீகரி',
    reject: 'நிராகரி',
    approvedSuccess: 'வெற்றிகரமாக அங்கீகரிக்கப்பட்டது',

    signIn: 'உள்நுழைக',
    residentSignUp: 'குடியிருப்பாளர் பதிவு',
    signInToSociety: 'சங்கத்தில் உள்நுழைக',
    createResidentAccount: 'புதிய கணக்கை உருவாக்கவும்',
    smartPortalSubtitle: 'ஸ்மார்ட் குடியிருப்பு சங்க போர்டல்',
    selectSociety: 'சங்கத்தைத் தேர்ந்தெடுக்கவும்',
    newSocietyQ: 'புதிய சங்கமா?',
    chooseSocietyPlaceholder: 'சங்கத்தைத் தேர்ந்தெடுக்கவும்...',
    availableSocieties: 'கிடைக்கும் சங்கங்கள்',
    searchSocietyPlaceholder: 'பெயர் அல்லது பின்கோடு தேடு...',
    societyPincode: 'சங்க பின்கோடு',
    availableWings: 'பிரிவுகள்',
    residentFullName: 'முழு பெயர்',
    mobileNumber: 'மொபைல் எண்',
    apartmentFlat: 'பிளாட் எண்',
    emailUsername: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    registrationSubmitted: 'பதிவு செய்யப்பட்டது',
    accessRestricted: 'அனுமதி கட்டுப்படுத்தப்பட்டுள்ளது',
    quickDemoLogins: 'டெமோ உள்நுழைவு',
    superAdmin: 'சூப்பர் அட்மின்',
    residentUser: 'குடியிருப்பாளர் பயனர்',
    registerNewSociety: 'புதிய சங்கத்தைப் பதிவுசெய்க',
    backToLanding: '← முகப்பு',

    landingHeroTitle: 'ஸ்மார்ட் குடியிருப்பு சங்க மேலாண்மை',
    landingHeroSubtitle: 'வசதி முன்பதிவு, பராமரிப்புக் கட்டணம், கேட் பாஸ் மற்றும் ஒருங்கிணைந்த மேலாண்மை.',
    signInPortal: 'போர்ட்டலில் நுழைக',
    registerSocietyBtn: 'சங்கத்தைப் பதிவுசெய்க',
    featuresTitle: 'முக்கிய அம்சங்கள்',
    featuresSubtitle: 'உங்கள் குடியிருப்புக்கான அனைத்து வசதிகளும் ஒரே இடத்தில்.',
    feature1Title: 'வசதி முன்பதிவு',
    feature1Desc: 'கிளப்ஹவுஸ் மற்றும் வசதிகளை உடனடியாக முன்பதிவு செய்யவும்.',
    feature2Title: 'பராமரிப்பு கட்டணம்',
    feature2Desc: 'கட்டணங்களை எளிதாக செலுத்தி ரசீது பெறவும்.',
    feature3Title: 'புகார் மையம்',
    feature3Desc: 'பிரச்சினைகளை விரைவாக தீர்க்க புகார் அளிக்கவும்.',
    feature4Title: 'அறிவிப்புகள்',
    feature4Desc: 'சங்க அறிவிப்புகளை உடனுக்குடன் பெறவும்.',
    feature5Title: 'கேட் பாஸ்',
    feature5Desc: 'பாதுகாப்பான QR கேட் பாஸ் வசதி.',
    feature6Title: 'சொத்து மேலாண்மை',
    feature6Desc: 'லிப்ட் மற்றும் உபகரணங்களின் முறையான பராமரிப்பு.',
    getStartedToday: 'இப்போதே தொடங்குங்கள்',
    joinSocieties: 'SocietyOne இல் இணையுங்கள்.',

    availableAmenities: 'கிடைக்கும் வசதிகள்',
    bookSlot: 'முன்பதிவு செய்யவும்',
    selectDate: 'தேதியைத் தேர்ந்தெடுக்கவும்',
    selectTimeSlot: 'நேரத்தைத் தேர்ந்தெடுக்கவும்',
    bookingConfirmed: 'முன்பதிவு உறுதியானது',
    charges: 'கட்டணம்',
    free: 'இலவசம்',
    paid: 'கட்டணம் செலுத்தப்பட்டது',
    perHour: 'ஒரு மணி நேரத்திற்கு',
    timeSlot: 'நேர இடைவெளி',
    residentName: 'குடியிருப்பாளர் பெயர்',
    amenityName: 'வசதி பெயர்',
    capacity: 'கொள்ளளவு',
    operatingHours: 'செயல்படும் நேரம்',
    rulesGuidelines: 'விதிகள்',
    myBookings: 'என் முன்பதிவுகள்',
    cancelBooking: 'முன்பதிவை ரத்து செய்',
    confirmAndBook: 'உறுதி செய்து முன்பதிவு செய்',

    raiseNewTicket: 'புதிய புகார் அளிக்கவும்',
    ticketCategory: 'வகை',
    ticketDescription: 'விளக்கம்',
    ticketUrgency: 'முக்கியத்துவம்',
    low: 'குறைந்த',
    medium: 'நடுத்தர',
    high: 'அதிக',
    emergency: 'அவசர',
    inProgress: 'செயலில்',

    communityLounge: 'சமூக அரட்டை',
    typeMessage: 'செய்தியைத் தட்டச்சு செய்க...',
    sendMessage: 'அனுப்பு'
  },
  te: {
    portalTitle: 'సొసైటీవన్ పోర్టల్',
    dashboard: 'డాష్‌బోర్డ్',
    management: 'నిర్వహణ',
    amenities: 'సౌకర్యాలు',
    residentsAndWings: 'నివాసితులు & విభాగాలు',
    financeAndAccounting: 'ఫైనాన్స్ & అకౌంట్స్',
    amcAndAssets: 'ఏఎంసీ & ఆస్తులు',
    vendors: 'విక్రేతలు',
    tendorManagement: 'టెండర్ నిర్వహణ',
    userManagement: 'యూజర్ మేనేజ్‌మెంట్',
    community: 'కమ్యూనిటీ',
    home: 'హోమ్',
    eventsAndNotices: 'ఈవెంట్లు & నోటీసులు',
    events: 'ఈవెంట్లు',
    fishBowl: 'ఫిష్ బౌల్ చాట్',
    services: 'సేవలు',
    facilityBooking: 'సౌకర్యాల బుకింగ్',
    helpdesk: 'హెల్ప్‌డెస్క్',
    signOut: 'లాగ్ అవుట్',
    search: 'వెతకండి',
    filter: 'ఫిల్టర్',
    all: 'అన్నీ',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    submit: 'సమర్పించండి',
    confirm: 'ధృవీకరించండి',
    close: 'మూసివేయండి',
    back: 'వెనుకకు',
    status: 'స్థితి',
    pending: 'పెండింగ్',
    approved: 'ఆమోదించబడింది',
    confirmed: 'ధృవీకరించబడింది',
    resolved: 'పరిష్కరించబడింది',
    open: 'ఓపెన్',
    closed: 'ముగిసింది',
    active: 'యాక్టివ్',
    completed: 'పూర్తయింది',
    language: 'భాష',
    selectLanguage: 'భాషను ఎంచుకోండి',
    pin: 'పిన్',

    welcomeBack: 'స్వాగతం',
    unitNo: 'యూనిట్',
    flat: 'ఫ్లాట్',
    wing: 'వింగ్',
    resident: 'నివాసి',
    quickActions: 'త్వరిత చర్యలు',
    payDues: 'బిల్లులు చెల్లించండి',
    bookAmenity: 'సౌకర్యాన్ని బుక్ చేయండి',
    raiseComplaint: 'ఫిర్యాదు చేయండి',
    myPasses: 'నా పాస్‌లు',
    societyNotices: 'సొసైటీ నోటీసులు',
    emergencyContacts: 'అత్యవసర పరిచయాలు',
    recentActivity: 'ఇటీవలి కార్యకలాపాలు',
    maintenance: 'మెయింటెనెన్స్',
    maintenanceDues: 'మెయింటెనెన్స్ బకాయిలు',
    upcomingEvents: 'రాబోయే ఈవెంట్లు',
    activeBookings: 'యాక్టివ్ బుకింగ్‌లు',
    noActiveBookings: 'ఇంకా బుకింగ్‌లు లేవు',
    noUpcomingEvents: 'రాబోయే ఈవెంట్లు లేవు',
    stayTunedEvents: 'కార్యక్రమాలు మరియు సమావేశాల వివరాలు ఇక్కడ కనిపిస్తాయి.',
    notificationsAndNotices: 'నోటీసులు మరియు సమాచారం',
    noNewNotifications: 'కొత్త నోటీసులు లేవు',
    noticesWillAppear: 'సొసైటీ నోటీసులు ఇక్కడ ప్రచురించబడతాయి.',
    myTickets: 'నా ఫిర్యాదులు',
    myTicketsSub: 'మీరు నమోదు చేసిన ఫిర్యాదులు',
    openTickets: 'ఓపెన్ ఫిర్యాదులు',
    openTicketsSub: 'ఇతర నివాసితుల ఫిర్యాదులు',
    noActiveTicketsUser: 'మీకు ఎటువంటి పెండింగ్ ఫిర్యాదులు లేవు',
    everythingSmooth: 'మీ ఫ్లాట్‌లో అంతా సవ్యంగా ఉంది.',
    needAssistance: 'సహాయం కావాలా? ఫిర్యాదు చేయండి',
    noOpenTicketsOther: 'ఇతర నివాసితుల నుండి ఫిర్యాదులు లేవు.',
    update: 'అప్‌డేట్',
    gatePass: 'గేట్ పాస్',
    verifiedPass: 'ధృవీకరించబడిన పాస్',
    securityGuard: 'సెక్యూరిటీ & గేట్',
    helpdeskSupport: 'హెల్ప్‌డెస్క్ సహాయం',
    rsvpDetails: 'వివరాలు చూడండి →',

    societyOverview: 'సొసైటీ సమీక్ష',
    totalRevenue: 'మొత్తం ఆదాయం',
    pendingApprovals: 'పెండింగ్ నివాసి ఆమోదాలు',
    awaiting: 'వేచి ఉంది',
    approveAccessText: 'లాగిన్ యాక్సెస్ ఇవ్వడానికి ఆమోదించండి.',
    allUsersAndRequests: 'వినియోగదారులందరూ',
    whatsHappening: 'ఈరోజు సొసైటీలో ముఖ్యాంశాలు:',
    approve: 'ఆమోదించు',
    reject: 'తిరస్కరించు',
    approvedSuccess: 'విజయవంతంగా ఆమోదించబడింది',

    signIn: 'సైన్ ఇన్',
    residentSignUp: 'నివాసి నమోదు',
    signInToSociety: 'సొసైటీలో లాగిన్ అవ్వండి',
    createResidentAccount: 'ఖాతాను సృష్టించండి',
    smartPortalSubtitle: 'స్మార్ట్ హౌసింగ్ సొసైటీ పోర్టల్',
    selectSociety: 'సొసైటీని ఎంచుకోండి',
    newSocietyQ: 'కొత్త సొసైటీనా?',
    chooseSocietyPlaceholder: 'సొసైటీని ఎంచుకోండి...',
    availableSocieties: 'అందుబాటులో ఉన్న సొసైటీలు',
    searchSocietyPlaceholder: 'పేరు, నగరం లేదా పిన్‌కోడ్ వెతకండి...',
    societyPincode: 'సొసైటీ పిన్‌కోడ్',
    availableWings: 'విభాగాలు',
    residentFullName: 'పూర్తి పేరు',
    mobileNumber: 'మొబైల్ నంబర్',
    apartmentFlat: 'ఫ్లాట్ నంబర్',
    emailUsername: 'ఈమెయిల్ / యూజర్‌నేమ్',
    password: 'పాస్‌వర్డ్',
    registrationSubmitted: 'నమోదు సమర్పించబడింది',
    accessRestricted: 'యాక్సెస్ పరిమితం',
    quickDemoLogins: 'డెమో లాగిన్లు',
    superAdmin: 'సూపర్ అడ్మిన్',
    residentUser: 'నివాసి వినియోగదారు',
    registerNewSociety: 'కొత్త సొసైటీని నమోదు చేయండి',
    backToLanding: '← ప్రధాన పేజీ',

    landingHeroTitle: 'స్మార్ట్ హౌసింగ్ సొసైటీ మేనేజ్‌మెంట్ ప్లాట్‌ఫారమ్',
    landingHeroSubtitle: 'సౌకర్యాల బుకింగ్, మెయింటెనెన్స్ బిల్లింగ్, డిజిటల్ గేట్ పాస్‌లతో మీ సొసైటీని స్మార్ట్‌గా మార్చండి.',
    signInPortal: 'పోర్టల్ లోకి ప్రవేశించండి',
    registerSocietyBtn: 'సొసైటీని నమోదు చేయండి',
    featuresTitle: 'ఆధునిక సొసైటీల కోసం ముఖ్య ఫీచర్లు',
    featuresSubtitle: 'మీ రెసిడెన్షియల్ కాంప్లెక్స్‌కు కావాల్సినవన్నీ ఒకే చోట.',
    feature1Title: 'త్వరిత సౌకర్యాల బుకింగ్',
    feature1Desc: 'క్లబ్‌హౌస్, జిమ్ మొదలైనవి సులభంగా బుక్ చేసుకోండి.',
    feature2Title: 'ఆటోమేటెడ్ బిల్లింగ్',
    feature2Desc: 'మెయింటెనెన్స్ బిల్లులను ఆన్‌లైన్‌లో చెల్లించండి.',
    feature3Title: 'డిజిటల్ హెల్ప్‌డెస్క్',
    feature3Desc: 'సమస్యలను వేగంగా పరిష్కరించడానికి ఫిర్యాదు చేయండి.',
    feature4Title: 'సొసైటీ నోటీసులు',
    feature4Desc: 'ముఖ్యమైన సమాచారం మరియు ఈవెంట్లను వెంటనే తెలుసుకోండి.',
    feature5Title: 'డిజిటల్ గేట్ పాస్‌లు',
    feature5Desc: 'అతిథులు మరియు సిబ్బందికి సురక్షిత QR పాస్.',
    feature6Title: 'ఆస్తుల నిర్వహణ',
    feature6Desc: 'లిఫ్టులు మరియు పరికరాల సమర్థవంతమైన నిర్వహణ.',
    getStartedToday: 'మీ సొసైటీని ఆధునీకరించడానికి సిద్ధంగా ఉన్నారా?',
    joinSocieties: 'ఈరోజే SocietyOne తో చేరండి.',

    availableAmenities: 'అందుబాటులో ఉన్న సౌకర్యాలు',
    bookSlot: 'స్లాట్ బుక్ చేయండి',
    selectDate: 'తేదీని ఎంచుకోండి',
    selectTimeSlot: 'సమయాన్ని ఎంచుకోండి',
    bookingConfirmed: 'బుకింగ్ ధృవీకరించబడింది',
    charges: 'ఛార్జీలు',
    free: 'ఉచితం',
    paid: 'చెల్లించబడింది',
    perHour: 'గంటకు',
    timeSlot: 'సమయ స్లాట్',
    residentName: 'నివాసి పేరు',
    amenityName: 'సౌకర్యం పేరు',
    capacity: 'సామర్థ్యం',
    operatingHours: 'సమయాలు',
    rulesGuidelines: 'నియమాలు',
    myBookings: 'నా బుకింగ్‌లు',
    cancelBooking: 'బుకింగ్‌ను రద్దు చేయండి',
    confirmAndBook: 'ధృవీకరించి బుక్ చేయండి',

    raiseNewTicket: 'కొత్త ఫిర్యాదు చేయండి',
    ticketCategory: 'వర్గం',
    ticketDescription: 'వివరణ',
    ticketUrgency: 'ప్రాధాన్యత',
    low: 'తక్కువ',
    medium: 'మధ్యస్థం',
    high: 'అధికం',
    emergency: 'అత్యవసరం',
    inProgress: 'పురోగతిలో ఉంది',

    communityLounge: 'కమ్యూనిటీ లాంజ్',
    typeMessage: 'సందేశాన్ని టైప్ చేయండి...',
    sendMessage: 'పంపండి'
  },
  kn: {
    portalTitle: 'ಸೊಸೈಟಿಒನ್ ಪೋರ್ಟಲ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    management: 'ನಿರ್ವಹಣೆ',
    amenities: 'ಸೌಲಭ್ಯಗಳು',
    residentsAndWings: 'ನಿವಾಸಿಗಳು ಮತ್ತು ವಿಭಾಗಗಳು',
    financeAndAccounting: 'ಹಣಕಾಸು ಮತ್ತು ಲೆಕ್ಕಪತ್ರ',
    amcAndAssets: 'ಎಎಂಸಿ ಮತ್ತು ಆಸ್ತಿಗಳು',
    vendors: 'ಮಾರಾಟಗಾರರು',
    tendorManagement: 'ಟೆಂಡರ್ ನಿರ್ವಹಣೆ',
    userManagement: 'ಬಳಕೆದಾರರ ನಿರ್ವಹಣೆ',
    community: 'ಸಮುದಾಯ',
    home: 'ಮುಖಪುಟ',
    eventsAndNotices: 'ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು ಸೂಚನೆಗಳು',
    events: 'ಕಾರ್ಯಕ್ರಮಗಳು',
    fishBowl: 'ಫಿಶ್ ಬೌಲ್ ಚಾಟ್',
    services: 'ಸೇವೆಗಳು',
    facilityBooking: 'ಸೌಲಭ್ಯ ಬುಕಿಂಗ್',
    helpdesk: 'ಸಹಾಯವಾಣಿ',
    signOut: 'ಸೈನ್ ಔಟ್',
    search: 'ಹುಡುಕಿ',
    filter: 'ಫಿಲ್ಟರ್',
    all: 'ಎಲ್ಲಾ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    submit: 'ಸಲ್ಲಿಸಿ',
    confirm: 'ದೃಢೀಕರಿಸಿ',
    close: 'ಮುಚ್ಚಿ',
    back: 'ಹಿಂದಕ್ಕೆ',
    status: 'ಸ್ಥಿತಿ',
    pending: 'ಬಾಕಿ ಇದೆ',
    approved: 'ಅನುಮೋದಿಸಲಾಗಿದೆ',
    confirmed: 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    resolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    open: 'ತೆರೆದಿದೆ',
    closed: 'ಮುಚ್ಚಲಾಗಿದೆ',
    active: 'ಸಕ್ರಿಯ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    language: 'ಭಾಷೆ',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    pin: 'ಪಿನ್',

    welcomeBack: 'ಸ್ವಾಗತ',
    unitNo: 'ಘಟಕ',
    flat: 'ಫ್ಲಾಟ್',
    wing: 'ವಿಭಾಗ',
    resident: 'ನಿವಾಸಿ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    payDues: 'ಬಿಲ್ ಪಾವತಿಸಿ',
    bookAmenity: 'ಸೌಲಭ್ಯ ಬುಕ್ ಮಾಡಿ',
    raiseComplaint: 'ದೂರು ದಾಖಲಿಸಿ',
    myPasses: 'ನನ್ನ ಪಾಸ್‌ಗಳು',
    societyNotices: 'ಸೊಸೈಟಿ ಸೂಚನೆಗಳು',
    emergencyContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    maintenance: 'ನಿರ್ವಹಣೆ',
    maintenanceDues: 'ನಿರ್ವಹಣೆ ಬಾಕಿ',
    upcomingEvents: 'ಮುಂಬರುವ ಕಾರ್ಯಕ್ರಮಗಳು',
    activeBookings: 'ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳು',
    noActiveBookings: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಬುಕಿಂಗ್ ಇಲ್ಲ',
    noUpcomingEvents: 'ಯಾವುದೇ ಮುಂಬರುವ ಕಾರ್ಯಕ್ರಮಗಳಿಲ್ಲ',
    stayTunedEvents: 'ಕಾರ್ಯಕ್ರಮಗಳ ವಿವರಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',
    notificationsAndNotices: 'ಸೂಚನೆಗಳು ಮತ್ತು ಮಾಹಿತಿ',
    noNewNotifications: 'ಹೊಸ ಸೂಚನೆಗಳಿಲ್ಲ',
    noticesWillAppear: 'ಸೊಸೈಟಿಯ ಸೂಚನೆಗಳು ಇಲ್ಲಿ ಪ್ರಕಟಗೊಳ್ಳುತ್ತವೆ.',
    myTickets: 'ನನ್ನ ದೂರುಗಳು',
    myTicketsSub: 'ನೀವು ದಾಖಲಿಸಿದ ದೂರುಗಳು',
    openTickets: 'ತೆರೆದ ದೂರುಗಳು',
    openTicketsSub: 'ಇತರ ನಿವಾಸಿಗಳ ದೂರುಗಳು',
    noActiveTicketsUser: 'ಯಾವುದೇ ಸಕ್ರಿಯ ದೂರುಗಳಿಲ್ಲ',
    everythingSmooth: 'ನಿಮ್ಮ ಮನೆಯಲ್ಲಿ ಎಲ್ಲವೂ ಸುಗಮವಾಗಿದೆ.',
    needAssistance: 'ಸಹಾಯ ಬೇಕೇ? ದೂರು ದಾಖಲಿಸಿ',
    noOpenTicketsOther: 'ಇತರರಿಂದ ಯಾವುದೇ ದೂರುಗಳಿಲ್ಲ.',
    update: 'ಅಪ್‌ಡೇಟ್',
    gatePass: 'ಗೇಟ್ ಪಾಸ್',
    verifiedPass: 'ದೃಢೀಕೃತ ಪಾಸ್',
    securityGuard: 'ಭದ್ರತೆ ಮತ್ತು ಗೇಟ್',
    helpdeskSupport: 'ಸಹಾಯವಾಣಿ ಬೆಂಬಲ',
    rsvpDetails: 'ವಿವರಗಳು →',

    societyOverview: 'ಸೊಸೈಟಿ ಅವಲೋಕನ',
    totalRevenue: 'ಒಟ್ಟು ಆದಾಯ',
    pendingApprovals: 'ಬಾಕಿ ಇರುವ ಅನುಮೋದನೆಗಳು',
    awaiting: 'ಕಾಯುತ್ತಿದೆ',
    approveAccessText: 'ಲಾಗಿನ್ ಅನುಮೋದಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ.',
    allUsersAndRequests: 'ಎಲ್ಲಾ ಬಳಕೆದಾರರು',
    whatsHappening: 'ಇಂದು ಸೊಸೈಟಿಯಲ್ಲಿ ಪ್ರಮುಖ ಘಟನೆಗಳು:',
    approve: 'ಅನುಮೋದಿಸಿ',
    reject: 'ತಿರಸ್ಕರಿಸಿ',
    approvedSuccess: 'ಯಶಸ್ವಿಯಾಗಿ ಅನುಮೋದಿಸಲಾಗಿದೆ',

    signIn: 'ಸೈನ್ ಇನ್',
    residentSignUp: 'ನಿವಾಸಿ ನೋಂದಣಿ',
    signInToSociety: 'ಸೊಸೈಟಿಗೆ ಲಾಗಿನ್ ಆಗಿ',
    createResidentAccount: 'ಖಾತೆ ರಚಿಸಿ',
    smartPortalSubtitle: 'ಸ್ಮಾರ್ಟ್ ಹೌಸಿಂಗ್ ಸೊಸೈಟಿ ಪೋರ್ಟಲ್',
    selectSociety: 'ಸೊಸೈಟಿ ಆಯ್ಕೆಮಾಡಿ',
    newSocietyQ: 'ಹೊಸ ಸೊಸೈಟಿಯೇ?',
    chooseSocietyPlaceholder: 'ಸೊಸೈಟಿ ಆಯ್ಕೆಮಾಡಿ...',
    availableSocieties: 'ಲಭ್ಯವಿರುವ ಸೊಸೈಟಿಗಳು',
    searchSocietyPlaceholder: 'ಹೆಸರು ಅಥವಾ ಪಿನ್‌ಕೋಡ್ ಹುಡುಕಿ...',
    societyPincode: 'ಸೊಸೈಟಿ ಪಿನ್‌ಕೋಡ್',
    availableWings: 'ವಿಭಾಗಗಳು',
    residentFullName: 'ಪೂರ್ಣ ಹೆಸರು',
    mobileNumber: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    apartmentFlat: 'ಫ್ಲಾಟ್ ಸಂಖ್ಯೆ',
    emailUsername: 'ಇಮೇಲ್ / ಬಳಕೆದಾರ ಹೆಸರು',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    registrationSubmitted: 'ನೋಂದಣಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
    accessRestricted: 'ಪ್ರವೇಶ ನಿರ್ಬಂಧಿಸಲಾಗಿದೆ',
    quickDemoLogins: 'ಡೆಮೊ ಲಾಗಿನ್',
    superAdmin: 'ಸೂಪರ್ ಅಡ್ಮಿನ್',
    residentUser: 'ನಿವಾಸಿ ಬಳಕೆದಾರ',
    registerNewSociety: 'ಹೊಸ ಸೊಸೈಟಿ ನೋಂದಾಯಿಸಿ',
    backToLanding: '← ಮುಖ್ಯ ಪುಟ',

    landingHeroTitle: 'ಸ್ಮಾರ್ಟ್ ಹೌಸಿಂಗ್ ಸೊಸೈಟಿ ನಿರ್ವಹಣಾ ವೇದಿಕೆ',
    landingHeroSubtitle: 'ಸೌಲಭ್ಯ ಬುಕಿಂಗ್, ನಿರ್ವಹಣಾ ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು ಡಿಜಿಟಲ್ ಗೇಟ್ ಪಾಸ್‌ಗಳೊಂದಿಗೆ ಸುಲಭ ನಿರ್ವಹಣೆ.',
    signInPortal: 'ಪೋರ್ಟಲ್‌ಗೆ ಪ್ರವೇಶಿಸಿ',
    registerSocietyBtn: 'ಸೊಸೈಟಿ ನೋಂದಾಯಿಸಿ',
    featuresTitle: 'ಮುಖ್ಯ ವೈಶಿಷ್ಟ್ಯಗಳು',
    featuresSubtitle: 'ನಿಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಬೇಕಾದ ಎಲ್ಲವೂ ಒಂದೇ ಕಡೆ.',
    feature1Title: 'ಸೌಲಭ್ಯ ಬುಕಿಂಗ್',
    feature1Desc: 'ಕ್ಲಬ್‌ಹೌಸ್ ಮತ್ತು ಕ್ರೀಡಾಂಗಣಗಳನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಬುಕ್ ಮಾಡಿ.',
    feature2Title: 'ನಿರ್ವಹಣಾ ಬಿಲ್ಲಿಂಗ್',
    feature2Desc: 'ಬಿಲ್ ಪಾವತಿಸಿ ಮತ್ತು ರಶೀದಿ ಪಡೆಯಿರಿ.',
    feature3Title: 'ಡಿಜಿಟಲ್ ಸಹಾಯವಾಣಿ',
    feature3Desc: 'ಸಮಸ್ಯೆಗಳ ಪರಿಹಾರಕ್ಕಾಗಿ ದೂರು ದಾಖಲಿಸಿ.',
    feature4Title: 'ಸೊಸೈಟಿ ಸೂಚನೆಗಳು',
    feature4Desc: 'ಮುಖ್ಯ ಸೂಚನೆಗಳನ್ನು ತಕ್ಷಣ ಪಡೆಯಿರಿ.',
    feature5Title: 'ಗೇಟ್ ಪಾಸ್',
    feature5Desc: 'ಸುರಕ್ಷಿತ QR ಗೇಟ್ ಪಾಸ್ ವ್ಯವಸ್ಥೆ.',
    feature6Title: 'ಆಸ್ತಿ ನಿರ್ವಹಣೆ',
    feature6Desc: 'ಉಪಕರಣಗಳ ಸಮರ್ಪಕ ನಿರ್ವಹಣೆ.',
    getStartedToday: 'ನಿಮ್ಮ ಸೊಸೈಟಿಯನ್ನು ಸ್ಮಾರ್ಟ್ ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
    joinSocieties: 'ಇಂದೇ SocietyOne ಗೆ ಸೇರಿ.',

    availableAmenities: 'ಲಭ್ಯವಿರುವ ಸೌಲಭ್ಯಗಳು',
    bookSlot: 'ಸ್ಲಾಟ್ ಬುಕ್ ಮಾಡಿ',
    selectDate: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
    selectTimeSlot: 'ಸಮಯ ಆಯ್ಕೆಮಾಡಿ',
    bookingConfirmed: 'ಬುಕಿಂಗ್ ದೃಢಪಟ್ಟಿದೆ',
    charges: 'ಶುಲ್ಕಗಳು',
    free: 'ಉಚಿತ',
    paid: 'ಪಾವತಿಸಲಾಗಿದೆ',
    perHour: 'ಪ್ರತಿ ಗಂಟೆಗೆ',
    timeSlot: 'ಸಮಯ ಸ್ಲಾಟ್',
    residentName: 'ನಿವಾಸಿಗಳ ಹೆಸರು',
    amenityName: 'ಸೌಲಭ್ಯದ ಹೆಸರು',
    capacity: 'ಸಾಮರ್ಥ್ಯ',
    operatingHours: 'ಸಮಯಾವಧಿ',
    rulesGuidelines: 'ನಿಯಮಗಳು',
    myBookings: 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
    cancelBooking: 'ಬುಕಿಂಗ್ ರದ್ದುಮಾಡಿ',
    confirmAndBook: 'ದೃಢೀಕರಿಸಿ ಬುಕ್ ಮಾಡಿ',

    raiseNewTicket: 'ಹೊಸ ದೂರು ದಾಖಲಿಸಿ',
    ticketCategory: 'ವರ್ಗ',
    ticketDescription: 'ವಿವರಣೆ',
    ticketUrgency: 'ಆದ್ಯತೆ',
    low: 'ಕಡಿಮೆ',
    medium: 'ಮಧ್ಯಮ',
    high: 'ಹೆಚ್ಚು',
    emergency: 'ತುರ್ತು',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',

    communityLounge: 'ಸಮುದಾಯ ಲಾಂಜ್',
    typeMessage: 'ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    sendMessage: 'ಕಳುಹಿಸಿ'
  },
  bn: {
    portalTitle: 'সোসাইটিওয়ান পোর্টাল',
    dashboard: 'ড্যাশবোর্ড',
    management: 'ব্যবস্থাপনা',
    amenities: 'সুবিধাসমূহ',
    residentsAndWings: 'বাসিন্দা ও উইং',
    financeAndAccounting: 'অর্থ ও হিসাব',
    amcAndAssets: 'এএমসি ও সম্পদ',
    vendors: 'বিক্রেতা',
    tendorManagement: 'টেন্ডার ব্যবস্থাপনা',
    userManagement: 'ব্যবহারকারী ব্যবস্থাপনা',
    community: 'সম্প্রদায়',
    home: 'হোম',
    eventsAndNotices: 'অনুষ্ঠান ও বিজ্ঞপ্তি',
    events: 'অনুষ্ঠান',
    fishBowl: 'ফিশ বাউল চ্যাট',
    services: 'সেবাসমূহ',
    facilityBooking: 'সুবিধা বুকিং',
    helpdesk: 'হেল্পডেস্ক',
    signOut: 'সাইন আউট',
    search: 'অনুসন্ধান',
    filter: 'ফিল্টার',
    all: 'সব',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    submit: 'জমা দিন',
    confirm: 'নিশ্চিত করুন',
    close: 'বন্ধ করুন',
    back: 'ফিরে যান',
    status: 'অবস্থা',
    pending: 'অপেক্ষারত',
    approved: 'অনুমোদিত',
    confirmed: 'নিশ্চিত',
    resolved: 'সমাধানকৃত',
    open: 'উন্মুক্ত',
    closed: 'বন্ধ',
    active: 'সক্রিয়',
    completed: 'সম্পূর্ণ',
    language: 'ভাষা',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    pin: 'পিন',

    welcomeBack: 'স্বাগতম',
    unitNo: 'ইউনিট',
    flat: 'ফ্ল্যাট',
    wing: 'উইং',
    resident: 'বাসিন্দা',
    quickActions: 'দ্রুত পদক্ষেপ',
    payDues: 'বিল দিন',
    bookAmenity: 'সুবিধা বুক করুন',
    raiseComplaint: 'অভিযোগ দায়ের করুন',
    myPasses: 'আমার পাস',
    societyNotices: 'সোসাইটি বিজ্ঞপ্তি',
    emergencyContacts: 'জরুরী যোগাযোগ',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    maintenance: 'রক্ষণাবেক্ষণ',
    maintenanceDues: 'বকেয়া রক্ষণাবেক্ষণ',
    upcomingEvents: 'আসন্ন অনুষ্ঠান',
    activeBookings: 'সক্রিয় বুকিং',
    noActiveBookings: 'কোনো সক্রিয় বুকিং নেই',
    noUpcomingEvents: 'কোনো আসন্ন অনুষ্ঠান নেই',
    stayTunedEvents: 'অনুষ্ঠান এবং সভার তথ্য এখানে পাওয়া যাবে।',
    notificationsAndNotices: 'বিজ্ঞপ্তি ও নোটিশ',
    noNewNotifications: 'কোনো নতুন বিজ্ঞপ্তি নেই',
    noticesWillAppear: 'সোসাইটির নোটিশ এখানে প্রকাশিত হবে।',
    myTickets: 'আমার অভিযোগ',
    myTicketsSub: 'আপনার দায়ের করা অভিযোগসমূহ',
    openTickets: 'উন্মুক্ত অভিযোগ',
    openTicketsSub: 'অন্যান্য বাসিন্দাদের অভিযোগ',
    noActiveTicketsUser: 'আপনার কোনো সক্রিয় অভিযোগ নেই',
    everythingSmooth: 'আপনার ফ্ল্যাটে সবকিছু স্বাভাবিক আছে।',
    needAssistance: 'সাহায্য দরকার? অভিযোগ দায়ের করুন',
    noOpenTicketsOther: 'অন্যান্য বাসিন্দাদের কোনো অভিযোগ নেই।',
    update: 'আপডেট',
    gatePass: 'গেট পাস',
    verifiedPass: 'যাচাইকৃত পাস',
    securityGuard: 'নিরাপত্তা ও গেট',
    helpdeskSupport: 'হেল্পডেস্ক সহায়তা',
    rsvpDetails: 'বিবরণ দেখুন →',

    societyOverview: 'সোসাইটি পর্যবেক্ষণ',
    totalRevenue: 'মোট আয়',
    pendingApprovals: 'অপেক্ষমান বাসিন্দা অনুমোদন',
    awaiting: 'অপেক্ষমান',
    approveAccessText: 'লগইন অনুমোদনের জন্য ক্লিক করুন।',
    allUsersAndRequests: 'সমস্ত ব্যবহারকারী',
    whatsHappening: 'আজ সোসাইটিতে কি ঘটছে:',
    approve: 'অনুমোদন করুন',
    reject: 'প্রত্যাখ্যান করুন',
    approvedSuccess: 'সফলভাবে অনুমোদিত হয়েছে',

    signIn: 'সাইন ইন',
    residentSignUp: 'বাসিন্দা নিবন্ধন',
    signInToSociety: 'সোসাইটিতে লগ ইন করুন',
    createResidentAccount: 'অ্যাকাউন্ট তৈরি করুন',
    smartPortalSubtitle: 'স্মার্ট হাউজিং সোসাইটি পোর্টাল',
    selectSociety: 'সোসাইটি নির্বাচন করুন',
    newSocietyQ: 'নতুন সোসাইটি?',
    chooseSocietyPlaceholder: 'সোসাইটি নির্বাচন করুন...',
    availableSocieties: 'উপলব্ধ সোসাইটিসমূহ',
    searchSocietyPlaceholder: 'নাম বা পিনকোড খুঁজুন...',
    societyPincode: 'সোসাইটি পিনকোড',
    availableWings: 'উইংসমূহ',
    residentFullName: 'বাসিন্দার পুরো নাম',
    mobileNumber: 'মোবাইল নম্বর',
    apartmentFlat: 'ফ্ল্যাট নম্বর',
    emailUsername: 'ইমেল / ব্যবহারকারীর নাম',
    password: 'পাসওয়ার্ড',
    registrationSubmitted: 'নিবন্ধন জমা দেওয়া হয়েছে',
    accessRestricted: 'প্রবেশাধিকার সীমাবদ্ধ',
    quickDemoLogins: 'ডেমো লগইন',
    superAdmin: 'সুপার অ্যাডমিন',
    residentUser: 'বাসিন্দা ব্যবহারকারী',
    registerNewSociety: 'নতুন সোসাইটি নিবন্ধন করুন',
    backToLanding: '← প্রধান পাতা',

    landingHeroTitle: 'স্মার্ট হাউজিং সোসাইটি পরিচালনা প্ল্যাটফর্ম',
    landingHeroSubtitle: 'সুবিধা বুকিং, রক্ষণাবেক্ষণ বিলিং এবং ডিজিটাল গেট পাস দিয়ে আপনার সোসাইটি পরিচালনা করুন সহজে।',
    signInPortal: 'পোর্টালে প্রবেশ করুন',
    registerSocietyBtn: 'সোসাইটি নিবন্ধন করুন',
    featuresTitle: 'প্রধান সুবিধাসমূহ',
    featuresSubtitle: 'আপনার আবাসিক এলাকার জন্য সবকিছু এক প্ল্যাটফর্মে।',
    feature1Title: 'সুবিধা বুকিং',
    feature1Desc: 'ক্লাবহাউস ও সুইমিং পুল সহজে বুক করুন।',
    feature2Title: 'রক্ষণাবেক্ষণ বিলিং',
    feature2Desc: 'অনলাইনে বিল পরিশোধ করুন এবং রসিদ পান।',
    feature3Title: 'ডিজিটাল হেল্পডেস্ক',
    feature3Desc: 'দ্রুত সমাধানের জন্য অভিযোগ দায়ের করুন।',
    feature4Title: 'সোসাইটি বিজ্ঞপ্তি',
    feature4Desc: 'গুরুত্বপূর্ণ নোটিশ সঙ্গে সঙ্গে পান।',
    feature5Title: 'ডিজিটাল গেট পাস',
    feature5Desc: 'অতিথি ও কর্মীদের জন্য নিরাপদ QR পাস।',
    feature6Title: 'সম্পদ ব্যবস্থাপনা',
    feature6Desc: 'যন্ত্রপাতি ও লিফটের নিয়মিত রক্ষণাবেক্ষণ।',
    getStartedToday: 'আপনার সোসাইটি আধুনিক করতে প্রস্তুত?',
    joinSocieties: 'আজই SocietyOne এর সাথে যুক্ত হোন।',

    availableAmenities: 'উপলব্ধ সুবিধাসমূহ',
    bookSlot: 'স্লট বুক করুন',
    selectDate: 'তারিখ নির্বাচন করুন',
    selectTimeSlot: 'সময় নির্বাচন করুন',
    bookingConfirmed: 'বুকিং নিশ্চিত হয়েছে',
    charges: 'চার্জ',
    free: 'বিনামূল্যে',
    paid: 'পরিশোধিত',
    perHour: 'প্রতি ঘণ্টা',
    timeSlot: 'সময় স্লট',
    residentName: 'বাসিন্দার নাম',
    amenityName: 'সুবিধার নাম',
    capacity: 'ধারণক্ষমতা',
    operatingHours: 'সময়সূচী',
    rulesGuidelines: 'নিয়মাবলী',
    myBookings: 'আমার বুকিং',
    cancelBooking: 'বুকিং বাতিল করুন',
    confirmAndBook: 'নিশ্চিত ও বুক করুন',

    raiseNewTicket: 'নতুন অভিযোগ দায়ের করুন',
    ticketCategory: 'বিভাগ',
    ticketDescription: 'বিবরণ',
    ticketUrgency: 'জরুরী অবস্থা',
    low: 'কম',
    medium: 'মাঝারি',
    high: 'উচ্চ',
    emergency: 'জরুরী',
    inProgress: 'চলমান',

    communityLounge: 'কমিউনিটি লাউঞ্জ',
    typeMessage: 'বার্তা লিখুন...',
    sendMessage: 'পাঠান'
  }
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
  supportedLanguages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType>({
  currentLanguage: 'en',
  setLanguage: () => {},
  t: (key: string, defaultText?: string) => defaultText || key,
  supportedLanguages: SUPPORTED_LANGUAGES
});

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem('societyone_lang');
      if (saved && (saved in translations)) {
        return saved as LanguageCode;
      }
    } catch (e) {
      // LocalStorage access fallback
    }
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    if (lang in translations) {
      setCurrentLanguageState(lang);
      try {
        localStorage.setItem('societyone_lang', lang);
      } catch (e) {
        // Ignore
      }
    }
  };

  const t = (key: string, defaultText?: string): string => {
    const langDict = translations[currentLanguage];
    if (langDict) {
      // 1. Direct key match
      if (langDict[key]) {
        return langDict[key];
      }
      // 2. Case-insensitive key match or trimmed
      const trimmedKey = key.trim();
      if (langDict[trimmedKey]) {
        return langDict[trimmedKey];
      }
      // 3. Match against defaultText if provided
      if (defaultText && langDict[defaultText]) {
        return langDict[defaultText];
      }
      if (defaultText && langDict[defaultText.trim()]) {
        return langDict[defaultText.trim()];
      }
    }

    // Fallback to English
    const fallbackDict = translations['en'];
    if (fallbackDict) {
      if (fallbackDict[key]) {
        return fallbackDict[key];
      }
      if (defaultText && fallbackDict[defaultText]) {
        return fallbackDict[defaultText];
      }
    }

    return defaultText !== undefined ? defaultText : key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, supportedLanguages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
